### ISSUE TITLE
0.26 Roadmap

### ISSUE THREAD

**Issue by wiiaam** [Antox/Antox#415]
Improvements to the UI:

- [ ] Fix GET links https://github.com/Antox/Antox/issues/314
- [ ] Profile pages (Long press on contact > view profile) should be improved
- [ ] Dark text with light themes https://github.com/Antox/Antox/issues/342
- [ ] AMOLED theme https://github.com/Antox/Antox/issues/334
- [ ] Theme is currently purple in MainActivity

Bugfixes: 

- [ ] Fix crashes due to nodefile https://github.com/Antox/Antox/issues/372 https://github.com/Antox/Antox/issues/327 https://github.com/Antox/Antox/issues/315
-[ ] Investigate various keyboard issues https://github.com/Antox/Antox/issues/323 https://github.com/Antox/Antox/issues/348

Improvements:

- [ ] QR code is being stored in SD card https://github.com/Antox/Antox/issues/320
- [ ] Support USB internet https://github.com/Antox/Antox/issues/317 - my USB to RJ45 adaptor has arrived so I will be able to test for this

More to be added

**Comment by SkyzohKey** [comment]
#413 is not an improvement, that's a bug.

**Comment by wiiaam** [comment]
A bug is when something doesn't work properly
An improvement is adding something that wasn't already implemented
